
JOBS:
  KRBUK-CNQDG:
    origin: KRBUK
    destination: CNQDG
  CNQDG-CNTXG:
    origin: CNQDG
    destination: CNTXG
  CNSZX-PHMNL:
    origin: CNSZX
    destination: PHMNL

DEFAULT_OUTPUT_FILE_DIRECTORY: "./output"