
FEATURES:
  - IMO
  - Latitude
  - Longitude
  - elapsed_time
  - week
  - remaining_lead_time

TARGET:
  - remaining_lead_time

LOGGING:
  level: DEBUG
  log_to_file: True
  local_log_file_directory: "/Users/Andrewlanders/projects/python_logs/"
