import os
import sys

class Environment:

    PATH = ".env"

    class Vars:
        CONFIG_PATH = "CONFIG_PATH"
        PATH_TO_PORTS_FILE = "PATH_TO_PORTS_FILE"
        PATH_TO_VESSEL_MOVEMENTS_DATA = "PATH_TO_VESSEL_MOVEMENTS_DATA"
        PATH_TO_OD_FILE = "PATH_TO_OD_FILE"
        PATH_TO_OUTPUT_DIRECTORY = "PATH_TO_OUTPUT_DIRECTORY"
        PATH_TO_LOG_FILE_DIRECTORY = "PATH_TO_LOG_FILE_DIRECTORY"
        PATH_TO_NEW_OD_REQUIREMENT_CSV_FILE = "PATH_TO_NEW_OD_REQUIREMENT_CSV_FILE"
        PATH_TO_COMBINED_OD_DATA = "PATH_TO_COMBINED_OD_DATA"
        PATH_TO_COMBINED_PORT_SEQUENCE_DATA = "PATH_TO_COMBINED_PORT_SEQUENCE_DATA"
        PATH_TO_SEAROUTES_UNLABELED_DATA = "PATH_TO_SEAROUTES_UNLABELED_DATA"
        PATH_TO_SEAROUTES_LABELED_DATA = "PATH_TO_SEAROUTES_LABELED_DATA"
        ODBC_DRIVER = "ODBC_DRIVER"
        SYNAPSE_SERVER = "SYNAPSE_SERVER"
        SYNAPSE_DATABASE = "SYNAPSE_DATABASE"
        SYNAPSE_UID = "SYNAPSE_UID"
        SYNAPSE_PASSWORD = "SYNAPSE_PASSWORD"
        SYNAPSE_SCHEMA = "SYNAPSE_SCHEMA"
        OCEAN_JOURNEY_CHUNK_CSV_FILE_DIR = "OCEAN_JOURNEY_CHUNK_CSV_FILE_DIR"
        OCEAN_JOURNEY_FEATURES_TABLE = "OCEAN_JOURNEY_FEATURES_TABLE"
        OCEAN_JOURNEY_RESPONSE_TABLE = "OCEAN_JOURNEY_RESPONSE_TABLE"
        OCEAN_JOURNEY_DATA_TABLE = "OCEAN_JOURNEY_DATA_TABLE"
        PATH_TO_LOCAL_TRAINING_DATA = "PATH_TO_LOCAL_TRAINING_DATA"
        BLOB_SERVICE_CONNECTION_STRING = "BLOB_SERVICE_CONNECTION_STRING"
        BLOB_SERVICE_ACCESS_KEY = "BLOB_SERVICE_ACCESS_KEY"
        BLOB_SERVICE_URL = "BLOB_SERVICE_URL"
        BLOB_SERVICE_CONTAINER_NAME = "BLOB_SERVICE_CONTAINER_NAME"
        OCEAN_JOURNEY_FEATURES_BLOB_SUBDIR = "OCEAN_JOURNEY_FEATURES_BLOB_SUBDIR"
        OCEAN_JOURNEY_RESPONSE_BLOB_SUBDIR = "OCEAN_JOURNEY_RESPONSE_BLOB_SUBDIR"
        OCEAN_PORTS_TABLE = "OCEAN_PORTS_TABLE"
        OCEAN_VESSELS_TABLE = "OCEAN_VESSELS_TABLE"

    @classmethod
    def set(cls):
        env_path: str = sys.argv[1].strip() if len(sys.argv) > 1 else cls.PATH
        with open(env_path, 'r') as env_file:
            for line in env_file.readlines():
                substrings = line.strip().split("=")
                var = substrings[0]
                value = "=".join(substrings[1:])
                os.environ[var] = value
